//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnderhillIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeID { get; set; }
        public string ClassroomURL { get; set; }
        public string AssignmentTitle { get; set; }
        public string StudentName { get; set; }
        public decimal PointsPossible { get; set; }
        public decimal PercentOfCourseGrade { get; set; }
        public decimal PointsAchieved { get; set; }
        public string EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
    }
}
